### ISSUE TITLE
获取token出错

### ISSUE THREAD

**Issue by NeoZZZZ** [mariotaku/twitter-tools#1]
使用删推工具，输入consumer key和secret以后，获取token出错：

`Traceback (most recent call last):
  File "F:\twitter\common.py", line 44, in get_access_token
    resp = oauth_client.fetch_request_token(REQUEST_TOKEN_URL)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests_oauthlib\oauth1_session.py", line 284, in fetch_request_token
    token = self._fetch_token(url, **request_kwargs)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests_oauthlib\oauth1_session.py", line 368, in _fetch_token
    raise TokenRequestDenied(error % (r.status_code, r.text), r)
requests_oauthlib.oauth1_session.TokenRequestDenied: Token request failed with code 401, response was '{"errors":[{"code":32,"message":"Could not authenticate you."}]}'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\twitter\nuke_tweet_archive.py", line 27, in <module>
    api = common.api()
  File "F:\twitter\common.py", line 108, in api
    credentials = get_credentials(credentials)
  File "F:\twitter\common.py", line 100, in get_credentials
    at, ats = get_access_token(ck, cs)
  File "F:\twitter\common.py", line 46, in get_access_token
    raise 'Invalid response from Twitter requesting temp token: {0}'.format(e)
TypeError: exceptions must derive from BaseException`

**Comment by mariotaku** [comment]
你的token是什么？如果Token是设置了Callback URL的，就无法使用

**Comment by NeoZZZZ** [comment]
我没有token，在Do you have access token and secret already?这一步选的N

**Comment by NeoZZZZ** [comment]
我去developer.twitter.com新建了个app用这个app的consumer key & secret和token 可以删除了，感谢！
